-- AlterTable
ALTER TABLE `ActivityEvent` MODIFY `type` ENUM('ACTIVITY_REMINDER', 'ACTIVITY_COMPLETED', 'ACTIVITY_CREATED', 'ACTIVITY_SKIPPED', 'ACTIVITY_UPDATED', 'ACTIVITY_DELETED', 'LOCATION_SHARED') NOT NULL;
