import type { DemoSeed } from '../demoSeedTypes';

const cloneDate = (date: Date) => new Date(date.getTime());

export const seniorDemoSeed: DemoSeed = {
  credentials: {
    email: 'senior.demo@cuidarte.app',
    password: 'CuidarteSenior123',
  },
  user: {
    id: 'demo-senior',
    email: 'senior.demo@cuidarte.app',
    name: 'Doña Carmen',
    role: 'senior',
    linkedUserId: 'demo-family',
  },
  activities: (() => {
    const today = new Date();
    const yesterday = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1);
    const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1);
    const nextDay = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 2);
    const nextWeek = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7);

    return [
      {
        id: 'demo-s-1',
        title: 'Tomar medicamento',
        description: 'Losartán 50mg y vitamina D',
        date: cloneDate(today),
        time: '08:00',
        type: 'medication',
        completed: true,
        evidenceRequired: 'button',
        evidencePhoto: 'photo-simulated',
        repeat: 'daily',
      },
      {
        id: 'demo-s-2',
        title: 'Desayuno saludable',
        description: 'Avena, fruta y té sin azúcar',
        date: cloneDate(today),
        time: '07:30',
        type: 'other',
        completed: true,
        evidenceRequired: 'photo',
        evidencePhoto: 'photo-simulated',
        repeat: 'daily',
      },
      {
        id: 'demo-s-3',
        title: 'Caminar 20 minutos',
        description: 'Paseo al aire libre con apoyo',
        date: cloneDate(today),
        time: '10:30',
        type: 'exercise',
        completed: true,
        evidenceRequired: 'location',
        repeat: 'daily',
      },
      {
        id: 'demo-s-4',
        title: 'Caminar 15 minutos',
        description: 'Actividad ligera por la mañana',
        date: cloneDate(today),
        time: '10:30',
        type: 'exercise',
        completed: false,
        evidenceRequired: 'location',
        repeat: 'daily',
      },
      {
        id: 'demo-s-5',
        title: 'Cita con cardiólogo',
        description: 'Consulta de seguimiento',
        date: cloneDate(today),
        time: '11:00',
        type: 'appointment',
        completed: false,
        evidenceRequired: 'photo',
        justification: 'La clínica la movió de horario',
        repeat: 'none',
      },
      {
        id: 'demo-s-6',
        title: 'Llamada con el médico',
        description: 'Seguimiento por teléfono',
        date: cloneDate(today),
        time: '12:15',
        type: 'appointment',
        completed: false,
        evidenceRequired: 'button',
        justification: 'No contestaron en el consultorio',
        repeat: 'none',
      },
      {
        id: 'demo-s-7',
        title: 'Llamar a la familia',
        description: 'Aviso de seguimiento diario',
        date: cloneDate(today),
        time: '18:00',
        type: 'social',
        completed: false,
        evidenceRequired: 'button',
        justification: 'No se pudo realizar la llamada',
        repeat: 'none',
      },
      {
        id: 'demo-s-8',
        title: 'Revisión de presión',
        description: 'Control semanal en casa',
        date: cloneDate(today),
        time: '08:40',
        type: 'other',
        completed: false,
        evidenceRequired: 'location',
        justification: 'No había quien acompañara a realizarla',
        repeat: 'weekly',
      },
      {
        id: 'demo-s-9',
        title: 'Caminar 15 minutos',
        description: 'Caminata ligera de la tarde',
        date: cloneDate(tomorrow),
        time: '17:30',
        type: 'exercise',
        completed: true,
        evidenceRequired: 'location',
        repeat: 'daily',
      },
    ];
  })(),
  contacts: [
    {
      id: 'demo-contact-1',
      name: 'María García',
      phone: '+52 664 123 4567',
      relationship: 'Hija',
    },
    {
      id: 'demo-contact-2',
      name: 'Carlos García',
      phone: '+52 664 234 5678',
      relationship: 'Hijo',
    },
    {
      id: 'demo-contact-3',
      name: 'Ana Torres',
      phone: '+52 664 345 6789',
      relationship: 'Nieta',
    },
    {
      id: 'demo-contact-4',
      name: 'Dr. José Ramírez',
      phone: '+52 664 456 7890',
      relationship: 'Médico',
    },
    {
      id: 'demo-contact-5',
      name: 'Lucía Hernández',
      phone: '+52 664 567 8901',
      relationship: 'Vecina',
    },
    {
      id: 'demo-contact-6',
      name: 'Pedro Sánchez',
      phone: '+52 664 678 9012',
      relationship: 'Hermano',
    },
  ],
  medications: [
    {
      id: 'demo-med-1',
      name: 'Losartán',
      dosage: '50mg',
      frequency: 'Diario',
      timing: 'before',
      times: ['08:00', '20:00'],
      stock: 12,
      minStock: 5,
    },
    {
      id: 'demo-med-2',
      name: 'Vitamina D',
      dosage: '1000 UI',
      frequency: 'Semanal',
      timing: 'after',
      times: ['09:00'],
      stock: 4,
      minStock: 3,
    },
  ],
  notifications: [
    {
      id: 'demo-sn-1',
      type: 'success',
      message: 'Tu familiar recibió la evidencia de la actividad de hoy',
      time: 'Hace 3 min',
      read: false,
    },
    {
      id: 'demo-sn-2',
      type: 'alert',
      message: 'Actividad pendiente: Cita con cardiólogo',
      time: 'Hace 20 min',
      read: false,
    },
    {
      id: 'demo-sn-3',
      type: 'info',
      message: 'Se compartió tu ubicación con la familia',
      time: 'Hace 1 hora',
      read: true,
    },
  ],
};